spring:
  datasource:
    username: postgres
    password: y1lfS31XjL6sB5e0EEsV
    url: jdbc:postgresql://containers-us-west-113.railway.app:6372/railway
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: false
app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    access_expiration: 86400
    refresh_expiration: 2592000
    tokenType: Bearer

