spring:
  datasource:
    username: gbgbzbwxmiacsn
    password: 91a721c6326eabf8d8b8e1cc452a3a299f0c1d3487df781f97fe7234ae27c579
    url: jdbc:postgres://gbgbzbwxmiacsn:91a721c6326eabf8d8b8e1cc452a3a299f0c1d3487df781f97fe7234ae27c579@ec2-44-205-41-76.compute-1.amazonaws.com:5432/d5t5i628vcr37n
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: false
server:
  port: 8000

app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    access_expiration: 86400
    refresh_expiration: 2592000
    tokenType: Bearer

