spring:
  datasource:
    username: postgres
    password: HdXR0InuQmc3s6tsJGU6
    url: jdbc:postgresql://containers-us-west-147.railway.app:6319/railway
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: false
app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    access_expiration: 86400
    refresh_expiration: 2592000
    tokenType: Bearer

