spring:
  datasource:
    username: postgres
    password: 20201996Rustam
    url: jdbc:postgresql://database-1.cd2mum8aexn8.us-east-1.rds.amazonaws.com/hero_clinic

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: false
app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    access_expiration: 86400
    refresh_expiration: 2592000
    tokenType: Bearer

