spring:
  datasource:
    username: postgres
    password: NpLBqauVkTxFcyLoCZJEmTgomhptExQg
    url: ${DB_URL:jdbc:postgresql://monorail.proxy.rlwy.net:24097/railway}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: false
app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    access_expiration: 86400
    refresh_expiration: 2592000
    tokenType: Bearer

