name: CICD

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t heroclinic/demo .
      - name: Publish image to docker hub
        run: docker push heroclinic/demo:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull heroclinic/demo:latest
      - name: Delete old container
        run: docker rm -f heroclinic-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name heroclinic-container heroclinic/demo
